import React from "react";
import { Scale, CheckCircle2, AlertOctagon, Lock } from "lucide-react";

interface DisclaimerModalProps {
  isOpen: boolean;
  onAccept: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, onAccept }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-md p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl max-w-xl w-full border border-sky-200 overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-sky-900 to-slate-900 text-white p-6 border-b border-sky-800 flex items-center gap-3">
          <div className="p-2.5 bg-sky-500/20 text-cyan-300 rounded-xl border border-teal-400/30">
            <Scale className="w-6 h-6 text-cyan-300" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white tracking-tight">Compliance & Legal Terms</h2>
            <p className="text-xs text-cyan-300 font-medium">Mandatory Acknowledgement Before Usage</p>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4 text-slate-700 text-sm leading-relaxed max-h-[60vh] overflow-y-auto">
          <div className="bg-sky-50/80 border border-sky-200 rounded-xl p-4 text-sky-900 flex items-start gap-3">
            <AlertOctagon className="w-5 h-5 text-sky-600 shrink-0 mt-0.5" />
            <p className="font-medium text-xs leading-relaxed text-slate-800">
              <strong className="text-sky-950">Mandatory Notice:</strong> This is a Legal Information Assistant, not a lawyer. Outputs are generated by an algorithmic model, do not constitute legal advice, and may contain errors. Please consult a licensed attorney for specific legal guidance.
            </p>
          </div>

          <div className="space-y-3 pt-2">
            <h3 className="font-bold text-slate-900 flex items-center gap-2 text-sm">
              <CheckCircle2 className="w-4 h-4 text-teal-600" /> Key Operating Principles
            </h3>

            <ul className="space-y-2.5 text-xs text-slate-600 pl-1">
              <li className="flex items-start gap-2.5">
                <span className="w-1.5 h-1.5 rounded-full bg-teal-500 mt-1.5 shrink-0" />
                <span><strong className="text-slate-900">Algorithmic Assistance:</strong> Summaries, translations, and risk scores (1-10) are produced by AI models (SaulLM-7B / Gemini / Claude) and may misinterpret complex jurisdictional nuances.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="w-1.5 h-1.5 rounded-full bg-sky-500 mt-1.5 shrink-0" />
                <span><strong className="text-slate-900">Data Privacy Pipeline:</strong> Documents undergo Microsoft Presidio PII masking before model evaluation to protect names, SSNs, and financials.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="w-1.5 h-1.5 rounded-full bg-teal-500 mt-1.5 shrink-0" />
                <span><strong className="text-slate-900">No Attorney-Client Privilege:</strong> Submitting documents does not establish an attorney-client relationship.</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Footer Action */}
        <div className="bg-sky-50/50 border-t border-sky-100 p-4 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2 text-xs text-slate-500">
            <Lock className="w-3.5 h-3.5 text-sky-600" /> Presidio Masking & Security Active
          </div>
          <button
            onClick={onAccept}
            className="px-5 py-2.5 bg-gradient-to-r from-sky-600 to-teal-500 hover:from-sky-500 hover:to-teal-400 text-white text-xs font-bold rounded-xl shadow-md transition cursor-pointer"
          >
            I Understand & Agree
          </button>
        </div>
      </div>
    </div>
  );
};

